# Generated by Django 2.2.5 on 2019-10-31 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'agentes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('busca_ambientes', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('busca_precio', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('busca_localidad', models.CharField(blank=True, default='San Miguel', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_venta', models.BooleanField()),
                ('apto_credito', models.BooleanField()),
                ('apto_profesional', models.BooleanField()),
                ('CP', models.PositiveIntegerField()),
                ('localidad', models.CharField(max_length=30)),
                ('partido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('entre', models.CharField(blank=True, max_length=70)),
                ('numero', models.PositiveIntegerField()),
                ('antiguedad', models.PositiveIntegerField(blank=True)),
                ('plano', models.BooleanField()),
                ('superficie_total', models.PositiveIntegerField()),
                ('superficie_semicubierta', models.PositiveIntegerField()),
                ('superficie_cubierta', models.PositiveIntegerField()),
                ('superficie_descubierta', models.PositiveIntegerField()),
                ('medida_frente', models.PositiveIntegerField(blank=True)),
                ('ambientes', models.PositiveIntegerField()),
                ('dormitorios', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField()),
                ('cochera', models.BooleanField()),
                ('gas', models.BooleanField(blank=True)),
                ('cloacas', models.BooleanField(blank=True)),
                ('asfalto', models.BooleanField(blank=True)),
                ('agua_corriente', models.BooleanField(blank=True)),
                ('descripcion', models.TextField(default='', max_length=300)),
                ('orientacion', models.CharField(blank=True, choices=[('n', 'Nor'), ('s', 'Sur'), ('e', 'Este'), ('o', 'Oeste'), ('no', 'Noroeste'), ('so', 'Sudoeste')], default='s', help_text='Orientacion del Inmueble', max_length=1)),
                ('zonificacion', models.CharField(blank=True, choices=[('u', 'Urbana'), ('r', 'Rural'), ('s', 'Semiurbana')], default='c', help_text='Zonificacion del Inmueble', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'verbose_name_plural': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Propiedad')),
                ('cant_plantas', models.PositiveIntegerField(blank=True)),
                ('pileta', models.BooleanField(blank=True)),
                ('barrio_privado', models.BooleanField(blank=True)),
            ],
            bases=('main.propiedad',),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Propiedad')),
                ('piso', models.PositiveIntegerField()),
                ('depto', models.CharField(blank=True, max_length=3)),
                ('expensas', models.PositiveIntegerField()),
                ('cant_pisos', models.PositiveIntegerField(blank=True)),
                ('cant_dptos_por_piso', models.PositiveIntegerField(blank=True)),
                ('encargado', models.BooleanField(blank=True)),
                ('seguridad', models.BooleanField(blank=True)),
                ('balcon', models.BooleanField()),
                ('ascensores', models.PositiveIntegerField()),
                ('vista', models.CharField(blank=True, choices=[('f', 'Frente'), ('c', 'Contrafrente'), ('l', 'Lateral'), ('i', 'Interno')], default='c', help_text='Vista del Inmueble', max_length=1)),
            ],
            bases=('main.propiedad',),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('agente', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad_Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='operacionbien', max_length=500)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('escribano', models.CharField(default='', max_length=40)),
                ('boleto', models.BooleanField(blank=True)),
                ('comprado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Propiedad')),
                ('vendido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Cliente')),
            ],
            options={
                'verbose_name_plural': 'operaciones',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
        ),
    ]
