# Generated by Django 2.2.5 on 2019-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='en_venta',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='medida_frente',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
    ]
