# Generated by Django 2.2.5 on 2019-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191116_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
