# Generated by Django 2.2.5 on 2019-11-16 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_propiedad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='publicada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
